//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebExample.WStest {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WStest.ExampleWSJSoap")]
    public interface ExampleWSJSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConutries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetConutries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConutries", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetConutriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomers", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetCustomersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertCustomer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool InsertCustomer(string CompanyName, string ContactName, string Address, string City, string PostalCode, string idCountry, string Phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> InsertCustomerAsync(string CompanyName, string ContactName, string Address, string City, string PostalCode, string idCountry, string Phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCustomer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DeleteCustomer(int CustomerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteCustomerAsync(int CustomerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCustomer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdateCustomer(int CustomerID, string CompanyName, string ContactName, string Address, string City, string PostalCode, string Country, string Phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> UpdateCustomerAsync(int CustomerID, string CompanyName, string ContactName, string Address, string City, string PostalCode, string Country, string Phone);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExampleWSJSoapChannel : WebExample.WStest.ExampleWSJSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExampleWSJSoapClient : System.ServiceModel.ClientBase<WebExample.WStest.ExampleWSJSoap>, WebExample.WStest.ExampleWSJSoap {
        
        public ExampleWSJSoapClient() {
        }
        
        public ExampleWSJSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExampleWSJSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExampleWSJSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExampleWSJSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Data.DataSet GetConutries() {
            return base.Channel.GetConutries();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetConutriesAsync() {
            return base.Channel.GetConutriesAsync();
        }
        
        public System.Data.DataSet GetCustomers() {
            return base.Channel.GetCustomers();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetCustomersAsync() {
            return base.Channel.GetCustomersAsync();
        }
        
        public bool InsertCustomer(string CompanyName, string ContactName, string Address, string City, string PostalCode, string idCountry, string Phone) {
            return base.Channel.InsertCustomer(CompanyName, ContactName, Address, City, PostalCode, idCountry, Phone);
        }
        
        public System.Threading.Tasks.Task<bool> InsertCustomerAsync(string CompanyName, string ContactName, string Address, string City, string PostalCode, string idCountry, string Phone) {
            return base.Channel.InsertCustomerAsync(CompanyName, ContactName, Address, City, PostalCode, idCountry, Phone);
        }
        
        public bool DeleteCustomer(int CustomerID) {
            return base.Channel.DeleteCustomer(CustomerID);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteCustomerAsync(int CustomerID) {
            return base.Channel.DeleteCustomerAsync(CustomerID);
        }
        
        public bool UpdateCustomer(int CustomerID, string CompanyName, string ContactName, string Address, string City, string PostalCode, string Country, string Phone) {
            return base.Channel.UpdateCustomer(CustomerID, CompanyName, ContactName, Address, City, PostalCode, Country, Phone);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateCustomerAsync(int CustomerID, string CompanyName, string ContactName, string Address, string City, string PostalCode, string Country, string Phone) {
            return base.Channel.UpdateCustomerAsync(CustomerID, CompanyName, ContactName, Address, City, PostalCode, Country, Phone);
        }
    }
}
